fix: logging message when PaymentID is None
Fix a "Logging error"
> TypeError: %d format: a number is required, not NoneType
fixes fccn/ecommerce-plugin-paygate#7